# Generated by Django 4.1.7 on 2023-03-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_picture',
            field=models.ImageField(blank=True, null=True, upload_to='account_picture/'),
        ),
    ]
