# Generated by Django 4.1.7 on 2023-03-29 09:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1', error_messages={'invalid': 'Please enter a valid phone number in the format +12125552368.'}, max_length=128, region=None),
        ),
    ]
