# Generated by Django 4.1.7 on 2023-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_string',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
