# Generated by Django 4.2 on 2023-04-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_userprofile_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='account_picture/user-default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
