# Generated by Django 4.2 on 2023-04-26 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_userprofileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='video_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.videosession'),
        ),
    ]
