# Generated by Django 4.2 on 2023-04-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_videosession_userprofileimage_video_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='images',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.userimage'),
        ),
    ]
