# Generated by Django 4.2 on 2023-04-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_userimage_alter_userprofileimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='temp_picture/'),
        ),
    ]
