# Generated by Django 4.2 on 2023-04-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='images',
            field=models.ImageField(upload_to='user_profile_images/'),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
