# Generated by Django 4.2 on 2023-04-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_userprofileimage_images_delete_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='base.userprofile'),
        ),
    ]
