# Generated by Django 4.2 on 2023-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_videosession_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embeddings',
            field=models.FileField(blank=True, null=True, upload_to='embeddings/'),
        ),
    ]
