# Generated by Django 4.2 on 2023-04-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_userprofile_embeddings_userprofile_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.account'),
        ),
    ]
